# Generated by Django 2.1.2 on 2018-11-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('company_reg', models.CharField(max_length=250)),
                ('compay_type', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('spoken_lang', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, upload_to='profile_image')),
                ('user_type', models.CharField(default='Company', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('job_type', models.CharField(max_length=250)),
                ('skill_required', models.CharField(max_length=2500)),
                ('desc', models.CharField(max_length=2500)),
                ('salary', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('nric', models.CharField(max_length=12)),
                ('skills', models.CharField(max_length=2500)),
                ('contact', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('user_type', models.CharField(default='Normal', max_length=10)),
            ],
        ),
    ]
