# Generated by Django 2.1.2 on 2018-11-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='compay_type',
            new_name='company_type',
        ),
    ]
