# Generated by Django 2.1.2 on 2018-11-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0002_auto_20181122_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='accessed_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobPostingWebsite.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_reg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='spoken_lang',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='town',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_type',
            field=models.CharField(default='Company', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='desc',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='skill_required',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nric',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Normal', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
