# Generated by Django 2.1.2 on 2018-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0003_auto_20181122_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='end_time',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='start_time',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
