# Generated by Django 2.1.2 on 2018-11-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0005_company_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobPostingWebsite.Jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobPostingWebsite.User')),
            ],
        ),
    ]
