# Generated by Django 2.1.2 on 2018-11-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0007_jobs_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
