# Generated by Django 2.1.2 on 2018-11-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0008_jobs_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
