# Generated by Django 2.1.2 on 2018-11-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0009_auto_20181123_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, null=True)),
                ('username', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=250, null=True)),
                ('user_type', models.CharField(default='Admin', max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
