# Generated by Django 2.1.2 on 2018-11-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0010_auto_20181123_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
