# Generated by Django 2.1.2 on 2018-11-24 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0011_jobs_is_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobPostingWebsite.JobType'),
        ),
    ]
