# Generated by Django 2.1.2 on 2018-11-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0014_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobPostingWebsite.JobCategory'),
        ),
    ]
