# Generated by Django 2.1.2 on 2018-11-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0016_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='img',
            field=models.ImageField(blank=True, default='img/logo.png', null=True, upload_to='profile_image'),
        ),
    ]
