# Generated by Django 2.1.2 on 2018-11-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostingWebsite', '0017_auto_20181125_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='img',
            field=models.ImageField(blank=True, default='profile_image/logo.jpg', null=True, upload_to='profile_image'),
        ),
    ]
